### PR TITLE
Update openmp check.

### PR DESCRIPTION
**Pull request by allisonvacanti**

### CODE REVIEW

**Comment by allisonvacanti** [comment]
run tests

**Comment by dkolsen-pgi** [comment]
That's definitely the right change.  But the name of the new macro hasn't been finalized yet.  I will wait to approve the PR to see if the name changes, though I won't wait more than a couple days.

**Comment by allisonvacanti** [comment]
Sounds good. I'm okay with merging this between the RC and the release if needed, so early next week would be fine.

**Comment by allisonvacanti** [comment]
DVS CL: 29629947

**Comment by allisonvacanti** [comment]
@dkolsen-pgi Have you decided on a final name for this?

**Review by dkolsen-pgi — APPROVED** [review]

**Comment by dkolsen-pgi** [comment]
Let's go with `_NV_STDPAR_OPENMP`.  I haven't made a final decision about names, but there is a good chance that one will fit into whatever pattern we settle on.

**Pull request merged**
