### PR TITLE
Remove dead code from expand.cu

### PR DESCRIPTION
**Pull request by lilohuang**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by allisonvacanti** [comment]
LGTM -- I'll get this merged soon. Thanks!

**Comment by lilohuang** [comment]
Hi @allisonvacanti ,

Somehow the deadcode is still in https://github.com/NVIDIA/thrust/blob/main/examples/expand.cu Perhaps, something went to wrong during merge?

Thanks,
Lilo

**Comment by allisonvacanti** [comment]
Ahh, this was targeted to the old `master` branch instead of `main`. I'll fix this up.

**Comment by allisonvacanti** [comment]
Cherry-picked to `main` in commit 892f5dbb7d142e6de2f42be6fc84880ad577761f.

**Pull request merged**
