### PR TITLE
thrust::iterator_traits to inherit from std::iterator_traits

### PR DESCRIPTION
**Pull request by divyegala**

### CODE REVIEW

**Comment by divyegala** [comment]
@allisonvacanti as discussed offline, here's the PR!

**Comment by allisonvacanti** [comment]
Thanks! LGTM, I'll start tests and merge this soon if all goes well.

DVS CL: 30202015

run tests

**Comment by divyegala** [comment]
@allisonvacanti could I get help for understanding why the tests fail only for `icc`?

**Comment by allisonvacanti** [comment]
Sorry, I should have mentioned -- the icc build is broken, this PR should be good to go.

I'll merge it today or tomorrow.

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
