### PR TITLE
Revert "update `SDK_VER` to match `cccl`"

### PR DESCRIPTION
**Pull request by senior-zero**
This reverts commit a3990be7a4181196c8ad4306e6aea0195d94e39c.

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Comment by miscco** [comment]
Is this still needed after https://github.com/NVIDIA/cccl/pull/20?

**Comment by senior-zero** [comment]
> Is this still needed after [NVIDIA/cccl#20](https://github.com/NVIDIA/cccl/pull/20)?

I think so

**Comment by miscco** [comment]
@ajschmidt8 Do you have any comments on this?

**Comment by ajschmidt8** [comment]
This PR can be merged now that https://github.com/NVIDIA/cccl/pull/20 has passed CI.

The new `11.5.1` containers should be published shortly.

**Comment by senior-zero** [comment]
run tests

**Comment by ajschmidt8** [comment]
run tests

**Comment by senior-zero** [comment]
Addressed by the following [PR](https://github.com/NVIDIA/thrust/pull/1874).

**Pull request closed without merging**
