### PR TITLE
Waive the reverse test “TestReverseCopySimple” when GCC8/9

### PR DESCRIPTION
**Pull request by veictry**
Nvbug
https://nvbugs/2481122
https://nvbugs/200735463

DVS-SC Virtual: https://scbuilds4u/dvs/#/change/3028503039432407.2?eventType=Virtual
Result Log: http://scvrlweb.nvidia.com/showjob.php?job=7213190

### CODE REVIEW

**Comment by veictry** [comment]
Hi @allisonvacanti 
I submitted the relevent PR, please help to review it. Thanks!

**Comment by allisonvacanti** [comment]
LGTM -- thanks for the PR!

I'll merge this once our tests pass.

DVS CL: 30442062

run tests

**Comment by veictry** [comment]
Thanks Allison!
I checked these failures and found that all failures are not related to reverse.cu.

Please help check them again if free time. Thanks!

**Comment by allisonvacanti** [comment]
There was an issue with non-GCC builds, I've pushed a fix for this. Restarting tests.

DVS CL: 30476835

run tests

**Comment by allisonvacanti** [comment]
NVC++ didn't like the new syntax. Trying again...

DVS CL: 30477150

run tests

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
