### PR TITLE
New Doxybook/Jekyll-based GitHub Pages documentation infrastructure (take two)

### PR DESCRIPTION
**Pull request by brycelelbach**
This PR (a revived version of #1475) introduces a new documentation infrastructure. It generates Doxygen XML output, and then uses the [Doxybook2](https://github.com/matusnovak/doxybook2) framework to generate GitHub Flavored Markdown. That GitHub Flavored Markdown is rendered using the Jekyll [just-the-docs](https://github.com/pmarsceill/just-the-docs) theme.

The final product is documentation in the style of the C++ Standard and [cppreference](https://cppreference.com) that can be deployed to GitHub Pages. For each class or Doxygen group, there is a code synopsis of all entities, followed by a section that contains detailed descriptions of them. Users can browse the docs using the sidebar or with just-the-docs powerful builtin search mechanism.

There are two scripts that can be used to locally build and host the docs:
* `docs/generate_markdown.bash`: This runs Doxygen and then Doxybook to generate the Markdown for the API docs.
* `docs/serve_jekyll_locally.bash`: This will start a local Jekyll server that will host the docs. You need to run `docs/generate_markdown.bash` first. Jekyll will build the HTML site when it starts, which takes a few minutes.

To build locally, you need to install Doxygen, Ruby (Debian package: `ruby-dev`), and Bundler (Debian package: `bundler`), which you should be able to do through your system's package manager.

You'll also need to build [Doxybook](https://github.com/matusnovak/doxybook2) from source, which is pretty easy to do. You'll need vcpkg to install Doxybook's dependencies - note that you'll need to specify `--head` when installing the inja dependency to ensure you get the correct version:

```
vcpkg install argagg catch2 fmt dirent fmt nlohmann-json rang
vcpkg install --head inja
```

Note that the above command install `inja` may fail within the NVIDIA VPN due to GitHub API rate limits (see Microsoft/vcpkg#19177). As an alternative, you can just grab and build [inja](github.com/pantor/inja), and then add the inja build directory to your `CMAKE_PREFIX_PATH` when building Doxybook.

Automated builds and deploy of the docs to GitHub pages are in place. The rendered docs from the tip of this branch can be seen at https://nvidia.github.io/thrust

### CODE REVIEW

**Comment by brycelelbach** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by brycelelbach** [comment]
run tests

**Comment by allisonvacanti** [comment]
DVS CL: 30976967

**Comment by brycelelbach** [comment]
Thanks Allison.

**Comment by brycelelbach** [comment]
gpuCI and DVS are passing, I think we are good to merge.

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
