### PR TITLE
remove deprecated support for the THRUST_DEVICE_BACKEND macro

### LINKED ISSUE #60: remove Thrust 1.6.0 deprecations
these aliases were deprecated in v1.6.0:
- `device_space_tag`
- `host_space_tag`
- `iterator_space`
- `any_space_tag`
- `THRUST_DEVICE_BACKEND`
- `THRUST_HOST_BACKEND`

Forwarded from http://code.google.com/p/thrust/issues/detail?id=466

### PR DESCRIPTION
**Pull request by ericniebler**
fixes #60

### CODE REVIEW

**Comment by ericniebler** [comment]
run tests

**Review by allisonvacanti — DISMISSED** [review]
These changes LGTM, but we'll need to also make the same change to `thrust/detail/config/host_system.h`.

**Comment by ericniebler** [comment]
> These changes LGTM, but we'll need to also make the same change to `thrust/detail/config/host_system.h`.

Uh, these _are_ the changes to `thrust/detail/config/host_system.h`. :confused:

**Comment by miscco** [comment]
> > These changes LGTM, but we'll need to also make the same change to `thrust/detail/config/host_system.h`.
> 
> Uh, these _are_ the changes to `thrust/detail/config/host_system.h`. 😕

Those changes live in `thrust/detail/config/device_system.h` 

The same code is also here https://github.com/NVIDIA/thrust/blob/0bebe52729380bf9260e272e1fadabfff9090ecf/thrust/detail/config/device_system.h#L36-L48

**Comment by ericniebler** [comment]
:man_facepalming: 

BTW, there is a comment in `thrust/memory.h` that references `THRUST_DEFAULT_DEVICE_BACKEND`. What should that be now?

**Comment by ericniebler** [comment]
run tests

**Review by miscco — APPROVED** [review]

**Pull request merged**
