### PR TITLE
Fix clang / nvcc CI build

### PR DESCRIPTION
**Pull request by senior-zero**
Clang has a builtin called `__is_signed`. Unfortunately, libstdc++ headers use this name as an identifier. Clang has a [workaround](https://github.com/llvm/llvm-project/blob/f49b6afc231242dfee027d5da69734836097cd43/clang/lib/Parse/ParseDecl.cpp#L3552-L3566) for that, it checks if `__is_signed` is `const static bool` as in libstdc++ headers and if so, disables the intrinsic for the rest of the TU. For some reason, when clang is used as host compiler in nvcc, this workaround doesn't work. It's likely that some implicitly included headers affect first use of `__is_signed`.

### CODE REVIEW

**Comment by senior-zero** [comment]
run tests

**Comment by jrhemstad** [comment]
@senior-zero for posterity, can you update the PR description with a summary of what we're doing here and why?

**Comment by senior-zero** [comment]
run tests

**Review by miscco — APPROVED** [review]

**Comment by senior-zero** [comment]
run tests

**Review by robertmaynard — CHANGES_REQUESTED** [review]

**Review by robertmaynard — APPROVED** [review]

**Comment by senior-zero** [comment]
run tests

**Comment by senior-zero** [comment]
run tests

**Comment by senior-zero** [comment]
run tests

**Pull request merged**
