### PR TITLE
update libcudacxx submodule to point to the 1.8.1 release

### PR DESCRIPTION
**Pull request by ericniebler**

### CODE REVIEW

**Comment by ericniebler** [comment]
run tests

**Comment by wmaxey** [comment]
Commit hash looks like the same as tag 1.8.1. LGTM.

**Review by wmaxey — APPROVED** [review]

**Comment by ericniebler** [comment]
@wmaxey can you make sense of the CI failures? I can't find any actual error in the logs, just: Aborted. :man_shrugging:

**Comment by wmaxey** [comment]
AFAICT icc might have timed out, perhaps a rerun would fix it.

**Comment by ericniebler** [comment]
run tests

**Pull request merged**
