### PR TITLE
Update CDP support macros for if-target compatibility

### PR DESCRIPTION
**Pull request by allisonvacanti**
Requires NVIDIA/cub#486.

This PR picks up where #1605 left off. It updates the CDP support in Thrust and CUB to eliminate the use of `__CUDA_ARCH__`. 

The CUDART macros have been revamped (see relnotes below), and a new `THRUST_CDP_DISPATCH` abstraction centralizes the logic used to dispatch between CDP parallel and sequential implementations based on RDC state.

The `testing/cuda/*` tests have been updated to check both parallel CDP launches with RDC enabled and sequential fallbacks when RDC is disabled.

# Pre-written Release Notes

## Breaking Changes

- NVIDIA/thrust#1661: Thrust’s CUDA Runtime support macros have been updated to support `NV_IF_TARGET`. They are now defined consistently across all host/device compilation passes. This should not affect most usages of these macros, but may require changes for some edge cases.
    - `THRUST_RUNTIME_FUNCTION`: Execution space annotations for functions that invoke CUDA Runtime APIs.
        - Old behavior:
            - RDC enabled: Defined to `__host__ __device__`
            - RDC not enabled:
                - NVCC host pass: Defined to `__host__ __device__`
                - NVCC device pass: Defined to `__host__`
        - New behavior:
            - RDC enabled: Defined to `__host__ __device__`
            - RDC not enabled: Defined to `__host__`
    - `__THRUST_HAS_CUDART__`: No change in behavior, but no longer used in Thrust. Provided for legacy support only. Legacy behavior:
        - RDC enabled: Defined to 1.
        - RDC not enabled:
            - NVCC host pass: Defined to 1.
            - NVCC device pass: Defined to 0.
    - `THRUST_RDC_ENABLED`: New macro, may be combined with `NV_IF_TARGET` to replace most usages of `__THRUST_HAS_CUDART__`. Behavior:
        - RDC enabled: Macro is defined.
        - RDC not enabled: Macro is not defined.

### CODE REVIEW

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Review by senior-zero — APPROVED** [review]

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Pull request merged**
