### PR TITLE
Do not merge; Testing NVIDIA/cub#405.

### PR DESCRIPTION
**Pull request by allisonvacanti**

### CODE REVIEW

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by zasdfgbnm** [comment]
CI failures seem unrelated?

**Comment by allisonvacanti** [comment]
> CI failures seem unrelated?

Yep, those had been failing for a long, long time. But good news, all gpuCI builders should be passing with the current `main` branch after some patches that just landed 🎉🎉🎉

**Pull request closed without merging**
