### PR TITLE
Support building the test suite without CUDA language enabled.

### PR DESCRIPTION
**Pull request by allisonvacanti**

### CODE REVIEW

**Comment by ahuynh-nvidia** [comment]
David asked me to review this PR. Looks good to me.

**Comment by allisonvacanti** [comment]
Thanks @ahuynh-nvidia!

**Comment by allisonvacanti** [comment]
I'll merge this in on Monday with the other last-minute 1.12.0 patches.

**Review by dkolsen-pgi — APPROVED** [review]

**Comment by dkolsen-pgi** [comment]
Can you merge it now so we can have it for our big weekend TA run that starts in a couple hours?

**Comment by allisonvacanti** [comment]
Sure, not a problem.

**Pull request merged**
