### PR TITLE
gpuCI updates

### PR DESCRIPTION
**Pull request by allisonvacanti**
I'm updating the gpuCI containers for nvbench, and figured I'd bump nvhpc since the 22.1 containers are out now.

@brycelelbach FYI

### CODE REVIEW

**Comment by allisonvacanti** [comment]
Will test once [images are ready](https://gpuci.gpuopenanalytics.com/job/nvidia/job/cccl/job/docker-main-branch/75/).

**Comment by allisonvacanti** [comment]
run tests

**Comment by brycelelbach** [comment]
LGTM.

**Review by brycelelbach — APPROVED** [review]

**Comment by allisonvacanti** [comment]
Respun the docker images to fix the clang12 builds (needed extra package for openmp).

run tests

**Comment by allisonvacanti** [comment]
Added a cub staging branch that pulls in the following fixes for gcc10 + gcc11:

- NVIDIA/cub#418
- NVIDIA/cub#420 (fixes NVIDIA/cub#419)
- NVIDIA/cub#421

run tests

**Comment by allisonvacanti** [comment]
DVS CL: 30883617

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
New DVS CL: 30884022

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
DVS CL: 30886324

**Pull request merged**
