### PR TITLE
Add option to enable all supported standards in for multiconfig.

### LINKED ISSUE #1321: Add `THRUST_MULTICONFIG_ENABLE_DIALECT_LATEST` CMake option for CI usecases
We want to build with the latest supported dialect for arbitrary nvcc + host compiler combinations.

- Add a `THRUST_MULTICONFIG_ENABLE_DIALECT_LATEST` CMake option
- When requested, run CMake try_compiles with different dialect flags
- Set the appropriate `THRUST_MULTICONFIG_ENABLE_DIALECT_XX` option

cc: @brycelelbach

### PR DESCRIPTION
**Pull request by allisonvacanti**
The THRUST_MULTICONFIG_ENABLE_DIALECT_ALL option will turn on all
dialects supported by the configured CXX / CUDA compilers.

Fixes #1321.

### CODE REVIEW

**Comment by allisonvacanti** [comment]
@brycelelbach Would this be a suitable implementation of #1321 for your needs? It enables all supported dialects, not just the latest. I can still add a mode that just enables the latest if needed.

I'll add this logic to CUB once this PR is approved.

**Comment by brycelelbach** [comment]
ok to test

**Comment by brycelelbach** [comment]
run tests

**Comment by brycelelbach** [comment]
This doesn't appear to work with NVC++. When building with this branch:

```
[11:40:33]:blelbach@dev-sky5:/home/blelbach/development/nvidia/thrust/build_nvcxx:0:$ cmake .. -DCMAKE_CUDA_COMPILER="/proj/nv/Linux_x86_64/dev/compilers/bin/nvc++" -DCMAKE_CUDA_COMPILER_FORCED=ON -DCMAKE_CUDA_COMPILER_ID="NVCXX" ..

-- The CXX compiler identification is PGI 99.99.198076
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /proj/nv/Linux_x86_64/dev/compilers/bin/nvc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Thrust: /home/blelbach/development/nvidia/thrust/thrust/cmake/thrust-config.cmake (found version "1.12.0.0")
-- Found CUB: /home/blelbach/development/nvidia/thrust/dependencies/cub/cub/cmake/cub-config.cmake (found version "1.12.0.0")
-- Thrust: TargetInfo: thrust: (1.12.0.0)
-- Thrust: TargetInfo: thrust > IMPORTED: TRUE
-- Thrust: TargetInfo: thrust > INTERFACE_LINK_LIBRARIES: Thrust::CPP::Host;Thrust::CUDA::Device
-- Performing Test CXX_FLAG__Werror
-- Performing Test CXX_FLAG__Werror - Success
-- Performing Test CXX_FLAG__Wall
-- Performing Test CXX_FLAG__Wall - Success
-- Performing Test CXX_FLAG__Wextra
-- Performing Test CXX_FLAG__Wextra - Success
-- Performing Test CXX_FLAG__Winit_self
-- Performing Test CXX_FLAG__Winit_self - Success
-- Performing Test CXX_FLAG__Woverloaded_virtual
-- Performing Test CXX_FLAG__Woverloaded_virtual - Failed
-- Performing Test CXX_FLAG__Wcast_qual
-- Performing Test CXX_FLAG__Wcast_qual - Success
-- Performing Test CXX_FLAG__Wno_cast_align
-- Performing Test CXX_FLAG__Wno_cast_align - Success
-- Performing Test CXX_FLAG__Wno_long_long
-- Performing Test CXX_FLAG__Wno_long_long - Success
-- Performing Test CXX_FLAG__Wno_variadic_macros
-- Performing Test CXX_FLAG__Wno_variadic_macros - Failed
-- Performing Test CXX_FLAG__Wno_unused_function
-- Performing Test CXX_FLAG__Wno_unused_function - Failed
-- Performing Test CXX_FLAG__Wno_unused_variable
-- Performing Test CXX_FLAG__Wno_unused_variable - Success
-- Enabling Thrust configuration: cpp.cuda.cpp14
-- CPP system found?  TRUE
-- CUDA system found? TRUE
-- TBB system found?  FALSE
-- OMP system found?  FALSE
-- Configuring done
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_sort_by_key".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_sort_by_key
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_sort".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_sort
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_reduce_by_key".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_reduce_by_key
CMake Error: Cannot determine link language for target "thrust.test.zip_function".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_function
CMake Error: Cannot determine link language for target "thrust.test.vector_insert".
CMake Error: CMake can not determine linker language for target: thrust.test.vector_insert
CMake Error: Cannot determine link language for target "thrust.test.vector_allocators".
CMake Error: CMake can not determine linker language for target: thrust.test.vector_allocators
CMake Error: Cannot determine link language for target "thrust.test.unique".
CMake Error: CMake can not determine linker language for target: thrust.test.unique
CMake Error: Cannot determine link language for target "thrust.test.uninitialized_copy".
CMake Error: CMake can not determine linker language for target: thrust.test.uninitialized_copy
CMake Error: Cannot determine link language for target "thrust.test.tuple_scan".
CMake Error: CMake can not determine linker language for target: thrust.test.tuple_scan
CMake Error: Cannot determine link language for target "thrust.test.tuple_reduce".
CMake Error: CMake can not determine linker language for target: thrust.test.tuple_reduce
```

This can be reproduced by building with `ci/local/build.bash -i gpuci/cccl:nvhpc20.9-devel-ubuntu20.04-nvcxx20.9`.

**Review by brycelelbach — CHANGES_REQUESTED** [review]
This doesn't appear to work with NVC++. When building with this branch:

```
[11:40:33]:blelbach@dev-sky5:/home/blelbach/development/nvidia/thrust/build_nvcxx:0:$ cmake .. \
  -DCMAKE_CUDA_COMPILER="/proj/nv/Linux_x86_64/dev/compilers/bin/nvc++" \
  -DCMAKE_CUDA_COMPILER_FORCED=ON \
  -DCMAKE_CUDA_COMPILER_ID="NVCXX" 

-- The CXX compiler identification is PGI 99.99.198076
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /proj/nv/Linux_x86_64/dev/compilers/bin/nvc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Thrust: /home/blelbach/development/nvidia/thrust/thrust/cmake/thrust-config.cmake (found version "1.12.0.0")
-- Found CUB: /home/blelbach/development/nvidia/thrust/dependencies/cub/cub/cmake/cub-config.cmake (found version "1.12.0.0")
-- Thrust: TargetInfo: thrust: (1.12.0.0)
-- Thrust: TargetInfo: thrust > IMPORTED: TRUE
-- Thrust: TargetInfo: thrust > INTERFACE_LINK_LIBRARIES: Thrust::CPP::Host;Thrust::CUDA::Device
-- Performing Test CXX_FLAG__Werror
-- Performing Test CXX_FLAG__Werror - Success
-- Performing Test CXX_FLAG__Wall
-- Performing Test CXX_FLAG__Wall - Success
-- Performing Test CXX_FLAG__Wextra
-- Performing Test CXX_FLAG__Wextra - Success
-- Performing Test CXX_FLAG__Winit_self
-- Performing Test CXX_FLAG__Winit_self - Success
-- Performing Test CXX_FLAG__Woverloaded_virtual
-- Performing Test CXX_FLAG__Woverloaded_virtual - Failed
-- Performing Test CXX_FLAG__Wcast_qual
-- Performing Test CXX_FLAG__Wcast_qual - Success
-- Performing Test CXX_FLAG__Wno_cast_align
-- Performing Test CXX_FLAG__Wno_cast_align - Success
-- Performing Test CXX_FLAG__Wno_long_long
-- Performing Test CXX_FLAG__Wno_long_long - Success
-- Performing Test CXX_FLAG__Wno_variadic_macros
-- Performing Test CXX_FLAG__Wno_variadic_macros - Failed
-- Performing Test CXX_FLAG__Wno_unused_function
-- Performing Test CXX_FLAG__Wno_unused_function - Failed
-- Performing Test CXX_FLAG__Wno_unused_variable
-- Performing Test CXX_FLAG__Wno_unused_variable - Success
-- Enabling Thrust configuration: cpp.cuda.cpp14
-- CPP system found?  TRUE
-- CUDA system found? TRUE
-- TBB system found?  FALSE
-- OMP system found?  FALSE
-- Configuring done
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_sort_by_key".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_sort_by_key
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_sort".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_sort
CMake Error: Cannot determine link language for target "thrust.test.zip_iterator_reduce_by_key".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_iterator_reduce_by_key
CMake Error: Cannot determine link language for target "thrust.test.zip_function".
CMake Error: CMake can not determine linker language for target: thrust.test.zip_function
CMake Error: Cannot determine link language for target "thrust.test.vector_insert".
CMake Error: CMake can not determine linker language for target: thrust.test.vector_insert
CMake Error: Cannot determine link language for target "thrust.test.vector_allocators".
CMake Error: CMake can not determine linker language for target: thrust.test.vector_allocators
CMake Error: Cannot determine link language for target "thrust.test.unique".
CMake Error: CMake can not determine linker language for target: thrust.test.unique
CMake Error: Cannot determine link language for target "thrust.test.uninitialized_copy".
CMake Error: CMake can not determine linker language for target: thrust.test.uninitialized_copy
CMake Error: Cannot determine link language for target "thrust.test.tuple_scan".
CMake Error: CMake can not determine linker language for target: thrust.test.tuple_scan
CMake Error: Cannot determine link language for target "thrust.test.tuple_reduce".
CMake Error: CMake can not determine linker language for target: thrust.test.tuple_reduce
```

This can be reproduced by building with `ci/local/build.bash -i gpuci/cccl:nvhpc20.9-devel-ubuntu20.04-nvcxx20.9`.

**Comment by brycelelbach** [comment]
Also, can this PR update gpuCI to use this new option? The three "coverage plans" in `ci/common/build.bash` will need to be updated to use this instead of hardcoding specific C++ dialects.

**Comment by allisonvacanti** [comment]
Per our discussion today:
- Also add a LATEST option (only latest, no other dialects)
- Implement for CUB, too.

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
- Added a `LATEST` option
- Updated the gpuCI scripts to use either `ALL` or `LATEST` dialects
- Verified that the new options are propagated to CUB when building CUB targets.

gpuCI is failing now, apparently calling `enable_language` from a function works on windows, but not on linux. I'll have to refactor this a bit more before it'll be ready.

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
run tests

**Comment by allisonvacanti** [comment]
Rewrote the dialect detection to check cmake properties instead of running try_compiles.

run tests

**Comment by allisonvacanti** [comment]
run tests

**Review by brycelelbach — APPROVED** [review]

**Pull request merged**
