### PR TITLE
Variadic make zip iterator

### LINKED ISSUE #663: variadic overload of make_zip_iterator
Would it make sense to add a variadic overload of `make_zip_iterator` that composes the existing `make_zip_iterator` with `make_tuple`?  I have this in my own code, and I find that it reduces syntactic overhead.

```
template<typename... Iterators>
__host__ __device__
  zip_iterator<thrust::tuple<Iterators...>> make_zip_iterator(thrust::tuple<Iterators...> t)
{
    return zip_iterator<thrust::tuple<Iterators...>>(t);
}


template<typename... Iterators>
__host__ __device__
  zip_iterator<thrust::tuple<Iterators...>> make_zip_iterator(Iterators... its)
{
    return make_zip_iterator(thrust::make_tuple(its...));
}
```

To disambiguate the single argument overloads, I replaced the existing overload for `IteratorTuple` with the one above that accepts `thrust::tuple<Iterators...>`.

### PR DESCRIPTION
**Pull request by andrewcorrigan**
Commit [5c5551c] would resolve #663 .  This is not dependent on the commits prior (already submitted via #1310), I just ended up committing it after those.

### CODE REVIEW

**Comment by allisonvacanti** [comment]
If this is independent of #1310, please rebase the branch to remove the overlapping commits. This will greatly simplify reviewing, testing, and integration.

**Review by allisonvacanti — CHANGES_REQUESTED** [review]
Per earlier comment, needs a rebase to remove commits from other PRs.

**Comment by andrewcorrigan** [comment]
Done.

**Comment by allisonvacanti** [comment]
Thanks!

LGTM, I'll start tests on this soon.

**Comment by andrewcorrigan** [comment]
I just pushed a commit that switches back to 2 spaces (the original commit gratuitously changed from 2 to 4).

**Comment by allisonvacanti** [comment]
Heh, yeah. I probably wouldn't have noticed the indentation :) We really need to pick a style and stick with it for Thrust and CUB.

DVS CL 29194412.

**Review by allisonvacanti — APPROVED** [review]

**Pull request merged**
